name: palace_core
version: 0.0.1+4
description: minimal server side dart micro-framework for building REST api easily
homepage: https://github.com/maxzod/
environment:
  sdk: ">=2.12.0 <3.0.0"
publish_to: "none"
dependencies:
  mime_type: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  dio: ^4.0.0
  pedantic: ^1.11.0
  test: ^1.16.8
